stages:
  - deploy

.docker-in-docker:
    tags:
      - docker-in-docker
    retry:
        max: 2
        when:
            - always
    image: pymor/docker-in-docker:d1b5ebb4dc42a77cae82411da2e503a88bb8fb3a
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    before_script:
        - 'export SHARED_PATH="${CI_PROJECT_DIR}/shared"'
        - mkdir -p ${SHARED_PATH}
    services:
        - docker:dind
    environment:
        name: unsafe

pages:
    extends: .docker-in-docker
    resource_group: pages
    stage: deploy
    script:
        - make CONFIG="_config.yml,_config_staging.yml"  build
        - make check
        - mv _site public
    only:
      - "2020_online"
    artifacts:
        paths:
            - public
