title: pyMOR School
description: > # this means to ignore newlines until "baseurl:"
  Model Order Reduction with Python
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://school.pymor.org" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "/css/2020_style/img/icon-large.png"


google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2020_pages', 'past/*']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
