title: pyMOR School
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "school.pymor.org" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "../css/2019_style/img/icon-large.png"


google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2019_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
